### ISSUE TITLE
Default to UTC during file import

### ISSUE THREAD

**Issue by michaelbrooks** [michaelbrooks/uw-message-coding#52]
Django complains if you insert datetimes into the database without setting the timezone. There's some stuff [here](https://docs.djangoproject.com/en/1.7/topics/i18n/timezones/).

**Comment by geosoco** [comment]
Hmmm. I'm not seeing warnings. Were you using the test_dataset.csv I sent out or something else? Did the format just not have the Z at the end or something? 

I could enable the pytz conversion stuff they mention in the article, but I'd like to know a little bit about what's causing it since that could lead to other problems.
